############################################################################
##
## Copyright 2024 lyint
##
## Лицензия Apache версии 2.0 («Лицензия»);
## вы не можете использовать этот файл, кроме как в соответствии с Лицензией.
## Вы можете получить копию Лицензии по адресу
##
## https://www.apache.org/licenses/LICENSE-2.0
##
## Если это не требуется действующим законодательством или не согласовано 
## в письменной форме, программное обеспечение распространяется по Лицензии,
## распространяется на условиях «КАК ЕСТЬ»,
## БЕЗ КАКИХ-ЛИБО ГАРАНТИЙ ИЛИ УСЛОВИЙ, явных или подразумеваемых.
## См. лицензию для конкретного языка, регулирующего разрешения и
## ограничения по Лицензии.
##
############################################################################

# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'remotron.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(450, 200)
        MainWindow.setMinimumSize(QtCore.QSize(450, 200))
        MainWindow.setMaximumSize(QtCore.QSize(450, 200))
        MainWindow.setStyleSheet(".QMainWindow {\n"
"   background-color: #393b3b;\n"
"   background-image: url(:/remotron/bg.jpg);\n"
"}\n"
"\n"
"QToolTip { \n"
"    background-color: #303030; \n"
"    color: white; \n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(110, -2, 391, 231))
        self.frame.setStyleSheet("* {border-radius: 1px;}\n"
"")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.comboBoxAdresses = QtWidgets.QComboBox(self.frame)
        self.comboBoxAdresses.setGeometry(QtCore.QRect(13, 41, 313, 22))
        self.comboBoxAdresses.setMinimumSize(QtCore.QSize(101, 0))
        self.comboBoxAdresses.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.comboBoxAdresses.setStyleSheet("QComboBox {\n"
"    border: 1px solid gray;\n"
"    border-radius: 3px;\n"
"    padding: 1px 18px 1px 3px;\n"
"    min-width: 6em;\n"
"}\n"
"\n"
"QComboBox:editable {\n"
"    background: #f2f2f2;\n"
"}\n"
"\n"
"QComboBox:!editable, QComboBox::drop-down:editable {\n"
"    background-color: #f2f2f2;\n"
"    text-align: center;\n"
"    color: #000000;\n"
"}\n"
"\n"
"QComboBox:!editable:on, QComboBox::drop-down:editable:on {\n"
"    background-color: #f2f2f2;\n"
"    color: #000000;\n"
"}\n"
"\n"
"QComboBox:on { \n"
"    padding-top: 3px;\n"
"    padding-left: 4px;\n"
"}\n"
"\n"
"QComboBox::drop-down {\n"
"    subcontrol-origin: padding;\n"
"    subcontrol-position: top right;\n"
"    width: 15px;\n"
"\n"
"    border-left-width: 1px;\n"
"    border-left-color: darkgray;\n"
"    border-left-style: solid;\n"
"    border-top-right-radius: 3px;\n"
"    border-bottom-right-radius: 3px;\n"
"}\n"
"\n"
"QComboBox::down-arrow:on { \n"
"    top: 1px;\n"
"    left: 1px;\n"
"}")
        self.comboBoxAdresses.setEditable(False)
        self.comboBoxAdresses.setCurrentText("")
        self.comboBoxAdresses.setIconSize(QtCore.QSize(16, 16))
        self.comboBoxAdresses.setObjectName("comboBoxAdresses")
        self.directInputLine = QtWidgets.QLineEdit(self.frame)
        self.directInputLine.setGeometry(QtCore.QRect(14, 90, 311, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.directInputLine.setFont(font)
        self.directInputLine.setStyleSheet("*{background-color: #f2f2f2;}\n"
"\n"
"QToolTip { \n"
"    background-color: #303030; \n"
"    color: white; \n"
"}")
        self.directInputLine.setAlignment(QtCore.Qt.AlignCenter)
        self.directInputLine.setObjectName("directInputLine")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.frame)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(14, 132, 311, 41))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.bottomButtonsLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.bottomButtonsLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.bottomButtonsLayout.setContentsMargins(0, 0, 0, 3)
        self.bottomButtonsLayout.setSpacing(5)
        self.bottomButtonsLayout.setObjectName("bottomButtonsLayout")
        self.vncButton = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.vncButton.setMinimumSize(QtCore.QSize(0, 24))
        self.vncButton.setMaximumSize(QtCore.QSize(200, 123))
        self.vncButton.setBaseSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.vncButton.setFont(font)
        self.vncButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.vncButton.setStyleSheet("*{background-color: #6a9c7c; color: white; font-weight: 600;}\n"
":pressed{background-color: none;}\n"
":hover{color: #dedede;}")
        self.vncButton.setObjectName("vncButton")
        self.bottomButtonsLayout.addWidget(self.vncButton)
        self.sshButton = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.sshButton.setMinimumSize(QtCore.QSize(0, 24))
        self.sshButton.setMaximumSize(QtCore.QSize(200, 123))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.sshButton.setFont(font)
        self.sshButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.sshButton.setStyleSheet("*{background-color: #424242; color: white; font-weight: 600;}\n"
":pressed{background-color: none;}\n"
":hover{color: #dedede;}")
        self.sshButton.setObjectName("sshButton")
        self.bottomButtonsLayout.addWidget(self.sshButton)
        self.rdpButton = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.rdpButton.setMinimumSize(QtCore.QSize(0, 24))
        self.rdpButton.setMaximumSize(QtCore.QSize(200, 123))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.rdpButton.setFont(font)
        self.rdpButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.rdpButton.setStyleSheet("*{background-color:#356994; color:white; font-weight: 600;}\n"
":pressed{background-color: none;}\n"
":hover{color: #dedede;}")
        self.rdpButton.setObjectName("rdpButton")
        self.bottomButtonsLayout.addWidget(self.rdpButton)
        self.customCommandButton = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.customCommandButton.setMinimumSize(QtCore.QSize(0, 24))
        self.customCommandButton.setMaximumSize(QtCore.QSize(200, 123))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.customCommandButton.setFont(font)
        self.customCommandButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.customCommandButton.setStyleSheet("*{background-color:#6a697a; color:white; font-weight: 600;}\n"
":pressed{background-color: none;}\n"
":hover{color: #dedede;}")
        self.customCommandButton.setObjectName("customCommandButton")
        self.bottomButtonsLayout.addWidget(self.customCommandButton)
        self.adminAlertButton = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.adminAlertButton.setMinimumSize(QtCore.QSize(0, 24))
        self.adminAlertButton.setMaximumSize(QtCore.QSize(200, 123))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.adminAlertButton.setFont(font)
        self.adminAlertButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.adminAlertButton.setStyleSheet("*{background-color:#697a7a; color:white; font-weight: 600;}\n"
":pressed{background-color: none;}\n"
":hover{color: #dedede;}")
        self.adminAlertButton.setObjectName("adminAlertButton")
        self.bottomButtonsLayout.addWidget(self.adminAlertButton)
        self.horizontalLayoutWidget_3 = QtWidgets.QWidget(self.frame)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(14, 69, 311, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.horizontalLayoutWidget_3.setFont(font)
        self.horizontalLayoutWidget_3.setStyleSheet("")
        self.horizontalLayoutWidget_3.setObjectName("horizontalLayoutWidget_3")
        self.quickSubnetChangeLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.quickSubnetChangeLayout.setContentsMargins(0, 0, 0, 0)
        self.quickSubnetChangeLayout.setSpacing(3)
        self.quickSubnetChangeLayout.setObjectName("quickSubnetChangeLayout")
        self.quickSubnetChange1 = QtWidgets.QPushButton(self.horizontalLayoutWidget_3)
        self.quickSubnetChange1.setMaximumSize(QtCore.QSize(29, 14))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.quickSubnetChange1.setFont(font)
        self.quickSubnetChange1.setStyleSheet("background-color: #f2f2f2;")
        self.quickSubnetChange1.setText("")
        self.quickSubnetChange1.setObjectName("quickSubnetChange1")
        self.quickSubnetChangeLayout.addWidget(self.quickSubnetChange1)
        self.quickSubnetChange2 = QtWidgets.QPushButton(self.horizontalLayoutWidget_3)
        self.quickSubnetChange2.setMaximumSize(QtCore.QSize(30, 14))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.quickSubnetChange2.setFont(font)
        self.quickSubnetChange2.setStyleSheet("background-color: #f2f2f2;")
        self.quickSubnetChange2.setText("")
        self.quickSubnetChange2.setObjectName("quickSubnetChange2")
        self.quickSubnetChangeLayout.addWidget(self.quickSubnetChange2)
        self.quickSubnetChange3 = QtWidgets.QPushButton(self.horizontalLayoutWidget_3)
        self.quickSubnetChange3.setMaximumSize(QtCore.QSize(29, 14))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.quickSubnetChange3.setFont(font)
        self.quickSubnetChange3.setStyleSheet("background-color: #f2f2f2;")
        self.quickSubnetChange3.setText("")
        self.quickSubnetChange3.setObjectName("quickSubnetChange3")
        self.quickSubnetChangeLayout.addWidget(self.quickSubnetChange3)
        self.quickSubnetChange4 = QtWidgets.QPushButton(self.horizontalLayoutWidget_3)
        self.quickSubnetChange4.setMaximumSize(QtCore.QSize(29, 14))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.quickSubnetChange4.setFont(font)
        self.quickSubnetChange4.setStyleSheet("background-color: #f2f2f2;")
        self.quickSubnetChange4.setText("")
        self.quickSubnetChange4.setObjectName("quickSubnetChange4")
        self.quickSubnetChangeLayout.addWidget(self.quickSubnetChange4)
        self.quickSubnetChange5 = QtWidgets.QPushButton(self.horizontalLayoutWidget_3)
        self.quickSubnetChange5.setMaximumSize(QtCore.QSize(29, 14))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.quickSubnetChange5.setFont(font)
        self.quickSubnetChange5.setStyleSheet("background-color: #f2f2f2;")
        self.quickSubnetChange5.setText("")
        self.quickSubnetChange5.setObjectName("quickSubnetChange5")
        self.quickSubnetChangeLayout.addWidget(self.quickSubnetChange5)
        self.quickSubnetChange6 = QtWidgets.QPushButton(self.horizontalLayoutWidget_3)
        self.quickSubnetChange6.setMaximumSize(QtCore.QSize(30, 14))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.quickSubnetChange6.setFont(font)
        self.quickSubnetChange6.setStyleSheet("background-color: #f2f2f2;")
        self.quickSubnetChange6.setText("")
        self.quickSubnetChange6.setObjectName("quickSubnetChange6")
        self.quickSubnetChangeLayout.addWidget(self.quickSubnetChange6)
        self.quickSubnetChange7 = QtWidgets.QPushButton(self.horizontalLayoutWidget_3)
        self.quickSubnetChange7.setMaximumSize(QtCore.QSize(29, 14))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.quickSubnetChange7.setFont(font)
        self.quickSubnetChange7.setStyleSheet("background-color: #f2f2f2;")
        self.quickSubnetChange7.setText("")
        self.quickSubnetChange7.setObjectName("quickSubnetChange7")
        self.quickSubnetChangeLayout.addWidget(self.quickSubnetChange7, 0, QtCore.Qt.AlignVCenter)
        self.quickSubnetChange8 = QtWidgets.QPushButton(self.horizontalLayoutWidget_3)
        self.quickSubnetChange8.setMaximumSize(QtCore.QSize(29, 14))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.quickSubnetChange8.setFont(font)
        self.quickSubnetChange8.setStyleSheet("background-color: #f2f2f2;")
        self.quickSubnetChange8.setText("")
        self.quickSubnetChange8.setObjectName("quickSubnetChange8")
        self.quickSubnetChangeLayout.addWidget(self.quickSubnetChange8)
        self.quickSubnetChange9 = QtWidgets.QPushButton(self.horizontalLayoutWidget_3)
        self.quickSubnetChange9.setMaximumSize(QtCore.QSize(29, 14))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.quickSubnetChange9.setFont(font)
        self.quickSubnetChange9.setStyleSheet("background-color: #f2f2f2;")
        self.quickSubnetChange9.setText("")
        self.quickSubnetChange9.setObjectName("quickSubnetChange9")
        self.quickSubnetChangeLayout.addWidget(self.quickSubnetChange9)
        self.quickSubnetChange10 = QtWidgets.QPushButton(self.horizontalLayoutWidget_3)
        self.quickSubnetChange10.setMaximumSize(QtCore.QSize(29, 14))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.quickSubnetChange10.setFont(font)
        self.quickSubnetChange10.setStyleSheet("background-color: #f2f2f2;")
        self.quickSubnetChange10.setText("")
        self.quickSubnetChange10.setObjectName("quickSubnetChange10")
        self.quickSubnetChangeLayout.addWidget(self.quickSubnetChange10)
        self.checkboxViewOnly = QtWidgets.QCheckBox(self.frame)
        self.checkboxViewOnly.setGeometry(QtCore.QRect(8, 17, 131, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(7)
        font.setBold(False)
        font.setWeight(50)
        self.checkboxViewOnly.setFont(font)
        self.checkboxViewOnly.setStyleSheet("padding-left: 5px;\n"
"color: white;")
        self.checkboxViewOnly.setObjectName("checkboxViewOnly")
        self.editAdressesButton = QtWidgets.QPushButton(self.frame)
        self.editAdressesButton.setGeometry(QtCore.QRect(260, 16, 31, 16))
        self.editAdressesButton.setMaximumSize(QtCore.QSize(91, 23))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.editAdressesButton.setFont(font)
        self.editAdressesButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.editAdressesButton.setStyleSheet("*{\n"
"background-color: #424242;\n"
"border-radius: 3px;\n"
"color: white;\n"
"}\n"
":pressed{background-color: none;}\n"
":hover{color: #dedede;}")
        self.editAdressesButton.setObjectName("editAdressesButton")
        self.bottomInfoButton = QtWidgets.QPushButton(self.frame)
        self.bottomInfoButton.setGeometry(QtCore.QRect(10, 180, 311, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(7)
        font.setBold(False)
        font.setWeight(50)
        self.bottomInfoButton.setFont(font)
        self.bottomInfoButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.bottomInfoButton.setStyleSheet("color: darkgray;")
        self.bottomInfoButton.setObjectName("bottomInfoButton")
        self.settingsButton = QtWidgets.QToolButton(self.frame)
        self.settingsButton.setGeometry(QtCore.QRect(320, 180, 21, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.settingsButton.setFont(font)
        self.settingsButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.settingsButton.setStyleSheet("color: #f2f2f2;")
        self.settingsButton.setObjectName("settingsButton")
        self.switchDatabaseButton = QtWidgets.QPushButton(self.frame)
        self.switchDatabaseButton.setEnabled(True)
        self.switchDatabaseButton.setGeometry(QtCore.QRect(205, 16, 51, 16))
        self.switchDatabaseButton.setMaximumSize(QtCore.QSize(51, 23))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.switchDatabaseButton.setFont(font)
        self.switchDatabaseButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.switchDatabaseButton.setStyleSheet("*{\n"
"background-color: #424242;\n"
"border-radius: 3px;\n"
"color: white;\n"
"}\n"
":pressed{background-color: none;}\n"
":hover{color: #dedede;}")
        self.switchDatabaseButton.setObjectName("switchDatabaseButton")
        self.recentButton = QtWidgets.QPushButton(self.frame)
        self.recentButton.setEnabled(True)
        self.recentButton.setGeometry(QtCore.QRect(150, 16, 51, 16))
        self.recentButton.setMaximumSize(QtCore.QSize(51, 23))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        self.recentButton.setFont(font)
        self.recentButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.recentButton.setStyleSheet("*{\n"
"background-color: #424242;\n"
"border-radius: 3px;\n"
"color: white;\n"
"}\n"
":pressed{background-color: none;}\n"
":hover{color: #dedede;}")
        self.recentButton.setObjectName("recentButton")
        self.saveAdressesButton = QtWidgets.QPushButton(self.frame)
        self.saveAdressesButton.setGeometry(QtCore.QRect(295, 16, 31, 16))
        self.saveAdressesButton.setMaximumSize(QtCore.QSize(95, 23))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.saveAdressesButton.setFont(font)
        self.saveAdressesButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.saveAdressesButton.setStyleSheet("*{\n"
"background-color: #424242;\n"
"border-radius: 3px;\n"
"color: white;\n"
"}\n"
":pressed{background-color: none;}\n"
":hover{color: #dedede;}")
        self.saveAdressesButton.setObjectName("saveAdressesButton")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 90, 111, 101))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.hotToolsLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.hotToolsLayout.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.hotToolsLayout.setContentsMargins(10, 0, 10, 0)
        self.hotToolsLayout.setSpacing(1)
        self.hotToolsLayout.setObjectName("hotToolsLayout")
        self.notepadButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.notepadButton.setMaximumSize(QtCore.QSize(100, 23))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(7)
        self.notepadButton.setFont(font)
        self.notepadButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.notepadButton.setStyleSheet("*{background-color: #5c5c5c; border-radius: 1px;padding: 5px; color: white;}\n"
":pressed{background-color: none;}\n"
":hover{color: #dedede;}")
        self.notepadButton.setObjectName("notepadButton")
        self.hotToolsLayout.addWidget(self.notepadButton)
        self.pingButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pingButton.setMaximumSize(QtCore.QSize(100, 23))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(7)
        self.pingButton.setFont(font)
        self.pingButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pingButton.setStyleSheet("*{background-color: #5c5c5c; border-radius: 1px;padding: 5px; color: white;}\n"
":pressed{background-color: none;}\n"
":hover{color: #dedede;}")
        self.pingButton.setObjectName("pingButton")
        self.hotToolsLayout.addWidget(self.pingButton)
        self.terminalButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.terminalButton.setMaximumSize(QtCore.QSize(100, 23))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(7)
        self.terminalButton.setFont(font)
        self.terminalButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.terminalButton.setStyleSheet("*{background-color: #5c5c5c; border-radius: 1px;padding: 5px; color: white;}\n"
":pressed{background-color: none;}\n"
":hover{color: #dedede;}")
        self.terminalButton.setObjectName("terminalButton")
        self.hotToolsLayout.addWidget(self.terminalButton)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(-1, 3, -1, -1)
        self.horizontalLayout.setSpacing(4)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.customUserCommand1 = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.customUserCommand1.setMaximumSize(QtCore.QSize(95, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.customUserCommand1.setFont(font)
        self.customUserCommand1.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.customUserCommand1.setStyleSheet("*{\n"
"background-color: #5c5c5c;\n"
"border-radius: 3px;\n"
"color: white;\n"
"}\n"
":pressed{background-color: none;}\n"
":hover{color: #dedede;}")
        self.customUserCommand1.setObjectName("customUserCommand1")
        self.horizontalLayout.addWidget(self.customUserCommand1)
        self.customUserCommand2 = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.customUserCommand2.setMaximumSize(QtCore.QSize(95, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.customUserCommand2.setFont(font)
        self.customUserCommand2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.customUserCommand2.setStyleSheet("*{\n"
"background-color: #5c5c5c;\n"
"border-radius: 3px;\n"
"color: white;\n"
"}\n"
":pressed{background-color: none;}\n"
":hover{color: #dedede;}")
        self.customUserCommand2.setObjectName("customUserCommand2")
        self.horizontalLayout.addWidget(self.customUserCommand2)
        self.customUserCommand3 = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.customUserCommand3.setMaximumSize(QtCore.QSize(95, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.customUserCommand3.setFont(font)
        self.customUserCommand3.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.customUserCommand3.setStyleSheet("*{\n"
"background-color: #5c5c5c;\n"
"border-radius: 3px;\n"
"color: white;\n"
"}\n"
":pressed{background-color: none;}\n"
":hover{color: #dedede;}")
        self.customUserCommand3.setObjectName("customUserCommand3")
        self.horizontalLayout.addWidget(self.customUserCommand3)
        self.customUserCommand4 = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.customUserCommand4.setMaximumSize(QtCore.QSize(95, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.customUserCommand4.setFont(font)
        self.customUserCommand4.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.customUserCommand4.setStyleSheet("*{\n"
"background-color: #5c5c5c;\n"
"border-radius: 3px;\n"
"color: white;\n"
"}\n"
":pressed{background-color: none;}\n"
":hover{color: #dedede;}")
        self.customUserCommand4.setObjectName("customUserCommand4")
        self.horizontalLayout.addWidget(self.customUserCommand4)
        self.hotToolsLayout.addLayout(self.horizontalLayout)
        self.sshAuthTitleLabel = QtWidgets.QLabel(self.centralwidget)
        self.sshAuthTitleLabel.setGeometry(QtCore.QRect(0, 3, 111, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(7)
        self.sshAuthTitleLabel.setFont(font)
        self.sshAuthTitleLabel.setStyleSheet("color: white;")
        self.sshAuthTitleLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.sshAuthTitleLabel.setObjectName("sshAuthTitleLabel")
        self.sshAuthPasswordLabel = QtWidgets.QLabel(self.centralwidget)
        self.sshAuthPasswordLabel.setGeometry(QtCore.QRect(10, 46, 31, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(7)
        self.sshAuthPasswordLabel.setFont(font)
        self.sshAuthPasswordLabel.setStyleSheet("color: white;")
        self.sshAuthPasswordLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.sshAuthPasswordLabel.setObjectName("sshAuthPasswordLabel")
        self.sshAuthPasswordInput = QtWidgets.QLineEdit(self.centralwidget)
        self.sshAuthPasswordInput.setGeometry(QtCore.QRect(50, 46, 51, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.sshAuthPasswordInput.setFont(font)
        self.sshAuthPasswordInput.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.sshAuthPasswordInput.setStyleSheet("border-radius: 1px; padding-left: 5px;\n"
"background-color: #f2f2f2;")
        self.sshAuthPasswordInput.setInputMethodHints(QtCore.Qt.ImhHiddenText|QtCore.Qt.ImhNoAutoUppercase|QtCore.Qt.ImhNoPredictiveText|QtCore.Qt.ImhSensitiveData)
        self.sshAuthPasswordInput.setEchoMode(QtWidgets.QLineEdit.Password)
        self.sshAuthPasswordInput.setAlignment(QtCore.Qt.AlignCenter)
        self.sshAuthPasswordInput.setObjectName("sshAuthPasswordInput")
        self.sshAuthLoginLabel = QtWidgets.QLabel(self.centralwidget)
        self.sshAuthLoginLabel.setGeometry(QtCore.QRect(10, 26, 31, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(7)
        self.sshAuthLoginLabel.setFont(font)
        self.sshAuthLoginLabel.setStyleSheet("color: white;")
        self.sshAuthLoginLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.sshAuthLoginLabel.setObjectName("sshAuthLoginLabel")
        self.sshAuthPortLabel = QtWidgets.QLabel(self.centralwidget)
        self.sshAuthPortLabel.setGeometry(QtCore.QRect(10, 66, 31, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(7)
        self.sshAuthPortLabel.setFont(font)
        self.sshAuthPortLabel.setStyleSheet("color: white;")
        self.sshAuthPortLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.sshAuthPortLabel.setObjectName("sshAuthPortLabel")
        self.sshAuthPortInput = QtWidgets.QLineEdit(self.centralwidget)
        self.sshAuthPortInput.setGeometry(QtCore.QRect(50, 66, 51, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.sshAuthPortInput.setFont(font)
        self.sshAuthPortInput.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.sshAuthPortInput.setStyleSheet("border-radius: 1px; padding-left: 5px;\n"
"background-color: #f2f2f2;")
        self.sshAuthPortInput.setAlignment(QtCore.Qt.AlignCenter)
        self.sshAuthPortInput.setObjectName("sshAuthPortInput")
        self.sshAuthLoginInput = QtWidgets.QLineEdit(self.centralwidget)
        self.sshAuthLoginInput.setGeometry(QtCore.QRect(50, 26, 51, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.sshAuthLoginInput.setFont(font)
        self.sshAuthLoginInput.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.sshAuthLoginInput.setStyleSheet("border-radius: 1px; padding-left: 5px;\n"
"background-color: #f2f2f2;")
        self.sshAuthLoginInput.setAlignment(QtCore.Qt.AlignCenter)
        self.sshAuthLoginInput.setObjectName("sshAuthLoginInput")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Remotron"))
        self.comboBoxAdresses.setToolTip(_translate("MainWindow", "Сохраненные адреса"))
        self.directInputLine.setToolTip(_translate("MainWindow", "Введите ip адрес"))
        self.vncButton.setText(_translate("MainWindow", "VNC"))
        self.sshButton.setText(_translate("MainWindow", "SSH"))
        self.rdpButton.setText(_translate("MainWindow", "RDP"))
        self.customCommandButton.setText(_translate("MainWindow", "CMD"))
        self.adminAlertButton.setText(_translate("MainWindow", "ALERT"))
        self.checkboxViewOnly.setText(_translate("MainWindow", "Только просмотр (VNC)"))
        self.editAdressesButton.setText(_translate("MainWindow", "Ред."))
        self.bottomInfoButton.setText(_translate("MainWindow", "lyint"))
        self.settingsButton.setToolTip(_translate("MainWindow", "Изменить конфиг"))
        self.settingsButton.setText(_translate("MainWindow", "..."))
        self.switchDatabaseButton.setText(_translate("MainWindow", "Перекл."))
        self.recentButton.setText(_translate("MainWindow", "Журнал"))
        self.saveAdressesButton.setText(_translate("MainWindow", "Сохр."))
        self.notepadButton.setText(_translate("MainWindow", "Блокнот"))
        self.pingButton.setText(_translate("MainWindow", "Пинг"))
        self.terminalButton.setText(_translate("MainWindow", "Терминал"))
        self.customUserCommand1.setText(_translate("MainWindow", "c1"))
        self.customUserCommand2.setText(_translate("MainWindow", "c2"))
        self.customUserCommand3.setText(_translate("MainWindow", "c3"))
        self.customUserCommand4.setText(_translate("MainWindow", "c4"))
        self.sshAuthTitleLabel.setToolTip(_translate("MainWindow", "<html><head/><body><p style=\"color: black;\">Введите данные для подключения через SSH</p></body></html>"))
        self.sshAuthTitleLabel.setText(_translate("MainWindow", "SSH AUTH"))
        self.sshAuthPasswordLabel.setText(_translate("MainWindow", "passwd"))
        self.sshAuthLoginLabel.setText(_translate("MainWindow", "login"))
        self.sshAuthPortLabel.setText(_translate("MainWindow", "port"))
import resource_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
